import { ContentType } from './types';

export const content: ContentType = {
  tr: {
    title: "AI News Tracker",
    description: "Kripto para haberleri yapay zeka destekli takip sistemi",
    github: "GitHub'da İncele",
    features: "Özellikler",
    gptTitle: "GPT Destekli",
    gptDesc: "ChatGPT ile güçlendirilmiş haber analizi ve özetleme",
    realTimeTitle: "Gerçek Zamanlı",
    realTimeDesc: "Anlık haber takibi ve bildirimler",
    customTitle: "Özelleştirilebilir",
    customDesc: "Kişiselleştirilmiş haber akışı ve filtreler",
    team: "Takım",
    role: "Kurucu & Geliştirici",
    rights: "Tüm hakları saklıdır",
    privacy: "Gizlilik Politikası",
    about: "Hakkında",
    newsSources: "Haber Kaynakları",
    newsSourcesDesc: "Güvenilir kaynaklardan anlık haberler",
    poweredBy: "Destekleyenler",
    poweredByDesc: "Teknoloji ortaklarımız",
    aboutContent: [
      "AI News Tracker, kripto para piyasalarındaki haberleri yapay zeka destekli olarak takip eden ve analiz eden bir platformdur.",
      "Platform, ChatGPT ile güçlendirilmiş haber analizi ve özetleme özelliği sayesinde, kullanıcılara önemli gelişmeleri hızlı ve anlaşılır bir şekilde sunar.",
      "Gerçek zamanlı haber takibi ve bildirimler sayesinde, kullanıcılar piyasadaki gelişmelerden anında haberdar olur.",
      "Kişiselleştirilebilir haber akışı ve filtreler ile kullanıcılar, ilgilendikleri konulara odaklanabilir."
    ],
    donate: "Bağış Yap",
    buyMeACoffee: "Bana Bir Kahve Ismarla",
    cryptoDonate: "Kripto ile Bağış Yap",
    factualTitle: "Doğrulanmış Haberler",
    factualDesc: "Güvenilir kaynaklardan doğrulanmış haberler",
    investTitle: "Yatırım Fırsatları",
    investDesc: "Potansiyel yatırım fırsatlarını kaçırmayın",
    listingTitle: "Borsa Listeleme",
    listingDesc: "Yeni coin ve token listeleme haberleri",
    summaryTitle: "Haber Özetleri",
    summaryDesc: "Önemli haberlerin kısa özetleri",
    telegram: "Telegram Kanalımıza Katıl",
    binancePay: "Binance Pay ile Bağış Yap",
    alphaAccess: "Alpha Erişimi",
    days: "Gün",
    hours: "Saat",
    minutes: "Dakika",
    seconds: "Saniye",
    feedback: "Geri Bildirim",
    feedbackDesc: "Görüşlerinizi bizimle paylaşın",
    feedbackName: "İsim",
    feedbackEmail: "E-posta",
    feedbackMessage: "Mesaj",
    feedbackSubmit: "Gönder",
    lightMode: "Aydınlık Mod",
    darkMode: "Karanlık Mod",
    understood: "Anladım",
    binanceDonate: "Binance ile Bağış Yap",
    metamaskDonate: "MetaMask ile Bağış Yap",
    feedbackSuccess: "Geri bildiriminiz için teşekkürler!"
  },
  en: {
    title: "AI News Tracker",
    description: "AI-powered crypto news tracking system",
    github: "View on GitHub",
    features: "Features",
    gptTitle: "GPT Powered",
    gptDesc: "News analysis and summarization powered by ChatGPT",
    realTimeTitle: "Real-Time",
    realTimeDesc: "Instant news tracking and notifications",
    customTitle: "Customizable",
    customDesc: "Personalized news feed and filters",
    team: "Team",
    role: "Founder & Developer",
    rights: "All rights reserved",
    privacy: "Privacy Policy",
    about: "About",
    newsSources: "News Sources",
    newsSourcesDesc: "Instant news from reliable sources",
    poweredBy: "Powered By",
    poweredByDesc: "Our technology partners",
    aboutContent: [
      "AI News Tracker is a platform that tracks and analyzes crypto market news with AI support.",
      "Thanks to its ChatGPT-powered news analysis and summarization feature, the platform presents important developments to users quickly and comprehensibly.",
      "With real-time news tracking and notifications, users are instantly informed about market developments.",
      "With customizable news feed and filters, users can focus on topics they are interested in."
    ],
    donate: "Donate",
    buyMeACoffee: "Buy Me A Coffee",
    cryptoDonate: "Donate with Crypto",
    factualTitle: "Verified News",
    factualDesc: "Verified news from reliable sources",
    investTitle: "Investment Opportunities",
    investDesc: "Don't miss potential investment opportunities",
    listingTitle: "Exchange Listing",
    listingDesc: "New coin and token listing news",
    summaryTitle: "News Summaries",
    summaryDesc: "Brief summaries of important news",
    telegram: "Join Our Telegram Channel",
    binancePay: "Donate with Binance Pay",
    alphaAccess: "Alpha Access",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    feedback: "Feedback",
    feedbackDesc: "Share your thoughts with us",
    feedbackName: "Name",
    feedbackEmail: "Email",
    feedbackMessage: "Message",
    feedbackSubmit: "Submit",
    feedbackSuccess: "Thank you for your feedback!",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    understood: "I Understand",
    binanceDonate: "Donate with Binance",
    metamaskDonate: "Donate with MetaMask"
  }
}; 