import { ContentType } from './types';

export const content: ContentType = {
  tr: {
    title: "AI News Tracker",
    description: "Kripto para haberleri yapay zeka destekli takip sistemi",
    github: "GitHub'da İncele",
    features: "Özellikler",
    gptTitle: "GPT Destekli",
    gptDesc: "ChatGPT ile güçlendirilmiş haber analizi ve özetleme",
    realTimeTitle: "Gerçek Zamanlı",
    realTimeDesc: "Anlık haber takibi ve bildirimler",
    customTitle: "Özelleştirilebilir",
    customDesc: "Kişiselleştirilmiş haber akışı ve filtreler",
    team: "Takımımız",
    role: "Kurucu & Geliştirici",
    rights: "Tüm hakları saklıdır",
    privacy: "Gizlilik Politikası",
    about: "Hakkında",
    newsSources: "Haber Kaynakları",
    newsSourcesDesc: "Güvenilir kaynaklardan anlık haberler",
    poweredBy: "Destekleyenler",
    poweredByDesc: "AI News Tracker, ChatGPT'nin güçlü yapay zeka teknolojisini kullanarak size en güncel ve doğru kripto para haberlerini sunar.",
    aboutContent: [
      "AI News Tracker, kripto para piyasalarındaki haberleri yapay zeka destekli olarak takip eden ve analiz eden bir platformdur.",
      "Platform, ChatGPT ile güçlendirilmiş haber analizi ve özetleme özelliği sayesinde, kullanıcılara önemli gelişmeleri hızlı ve anlaşılır bir şekilde sunar.",
      "Gerçek zamanlı haber takibi ve bildirimler sayesinde, kullanıcılar piyasadaki gelişmelerden anında haberdar olur.",
      "Kişiselleştirilebilir haber akışı ve filtreler ile kullanıcılar, ilgilendikleri konulara odaklanabilir."
    ],
    donate: "Bağış Yap",
    buyMeACoffee: "Bir Kahve Ismarla",
    cryptoDonate: "Kripto ile Bağış Yap",
    factualTitle: "Doğrulanmış Haberler",
    factualDesc: "Güvenilir kaynaklardan doğrulanmış haberler",
    investTitle: "Yatırım Fırsatları",
    investDesc: "Potansiyel yatırım fırsatlarını kaçırmayın",
    listingTitle: "Borsa Listeleme",
    listingDesc: "Yeni coin ve token listeleme haberleri",
    summaryTitle: "Haber Özetleri",
    summaryDesc: "Önemli haberlerin kısa özetleri",
    telegram: "Telegram Kanalımıza Katıl",
    binancePay: "Binance Pay ile Bağış Yap",
    alphaAccess: "Alpha Erişimine Kalan Süre",
    days: "Gün",
    hours: "Saat",
    minutes: "Dakika",
    seconds: "Saniye",
    feedback: "Geri Bildirim",
    feedbackDesc: "Kanala katıldıktan sonra duygu ve düşüncelerinizi bizimle paylaşmanız çok önemli",
    feedbackName: "İsim",
    feedbackEmail: "E-posta",
    feedbackMessage: "Mesaj",
    feedbackSubmit: "Gönder",
    feedbackSuccess: "Geri bildiriminiz için teşekkür ederiz!",
    lightMode: "Aydınlık Mod",
    darkMode: "Karanlık Mod",
    understood: "Anladım",
    binanceDonate: "Binance ile Bağış Yap",
    metamaskDonate: "MetaMask ile Bağış Yap",
    founder: "Kurucu & Geliştirici"
  },
  en: {
    title: "AI News Tracker",
    description: "AI-powered crypto news tracking system",
    github: "View on GitHub",
    features: "Features",
    gptTitle: "GPT Powered",
    gptDesc: "News analysis and summarization powered by ChatGPT",
    realTimeTitle: "Real Time",
    realTimeDesc: "Instant news tracking and notifications",
    customTitle: "Customizable",
    customDesc: "Personalized news feed and filters",
    team: "Our Team",
    role: "Founder & Developer",
    rights: "All rights reserved",
    privacy: "Privacy Policy",
    about: "About",
    newsSources: "News Sources",
    newsSourcesDesc: "Real-time news from trusted sources",
    poweredBy: "Powered By",
    poweredByDesc: "AI News Tracker uses ChatGPT's powerful artificial intelligence technology to provide you with the most up-to-date and accurate cryptocurrency news.",
    aboutContent: [
      "AI News Tracker is a platform that tracks and analyzes crypto market news using artificial intelligence.",
      "The platform provides users with important developments quickly and comprehensibly through news analysis and summarization powered by ChatGPT.",
      "Users are instantly notified of market developments through real-time news tracking and notifications.",
      "Users can focus on topics they are interested in with customizable news feed and filters."
    ],
    donate: "Donate",
    buyMeACoffee: "Buy Me a Coffee",
    cryptoDonate: "Donate with Crypto",
    factualTitle: "Verified News",
    factualDesc: "Verified news from trusted sources",
    investTitle: "Investment Opportunities",
    investDesc: "Don't miss potential investment opportunities",
    listingTitle: "Exchange Listings",
    listingDesc: "New coin and token listing news",
    summaryTitle: "News Summaries",
    summaryDesc: "Brief summaries of important news",
    telegram: "Join Our Telegram Channel",
    binancePay: "Donate with Binance Pay",
    alphaAccess: "Time Left for Alpha Access",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    feedback: "Feedback",
    feedbackDesc: "After joining the channel, it's important to share your thoughts and feelings with us",
    feedbackName: "Name",
    feedbackEmail: "Email",
    feedbackMessage: "Message",
    feedbackSubmit: "Submit",
    feedbackSuccess: "Thank you for your feedback!",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    understood: "I Understand",
    binanceDonate: "Donate with Binance",
    metamaskDonate: "Donate with MetaMask",
    founder: "Founder & Developer"
  }
} as const; 