const tr = {
  title: "Başlık",
  description: "Açıklama",
  telegram: "Telegram",
  joinTelegram: "Telegrama Katıl",
  telegramModalTitle: "Telegram'a Katılın",
  telegramModalDescription: "Detayları görmek için Telegram grubuna katılın",
  cancel: "İptal",
  feedbackSuccess: "Geri bildirim gönderildi",
  feedback: "Geri bildirim",
  feedbackDesc: "Geri bildirim açıklaması",
  understood: "Anladım",
  github: "Github",
  features: "Özellikler",
  allInOne: "Hepsi Bir Arada",
  allInOneDesc: "Açıklama",
  gptTitle: "GPT Başlığı",
  gptDesc: "GPT Açıklaması",
  realTimeTitle: "Gerçek Zamanlı Başlık",
  realTimeDesc: "Gerçek Zamanlı Açıklama",
  customTitle: "Özel Başlık",
  customDesc: "Özel Açıklama",
  team: "Takım",
  role: "Rol",
  rights: "Haklar",
  privacy: "Gizlilik",
  about: "Hakkında",
  newsSources: "Haber Kaynakları",
  newsSourcesDesc: "Haber kaynakları açıklaması",
  poweredBy: "Destekleyen",
  poweredByDesc: "Destek açıklaması",
  aboutContent: ["Parça 1", "Parça 2"],
  donate: "Bağış Yap",
  buyMeACoffee: "Bir Kahve Al",
  cryptoDonate: "Kripto Bağış",
  factualTitle: "Factual Başlık",
  factualDesc: "Factual Açıklama",
  investTitle: "Yatırım Başlığı",
  investDesc: "Yatırım Açıklaması",
  listingTitle: "Liste Başlığı",
  listingDesc: "Liste Açıklaması",
  summaryTitle: "Özet Başlık",
  summaryDesc: "Özet Açıklama",
  binancePay: "Binance Pay",
  alphaAccess: "Alpha Erişim",
  days: "Gün",
  hours: "Saat",
  minutes: "Dakika",
  seconds: "Saniye",
  feedbackName: "İsim",
  feedbackEmail: "E-posta",
  feedbackMessage: "Mesaj",
  feedbackSubmit: "Gönder",
  lightMode: "Açık Mod",
  darkMode: "Koyu Mod",
  binanceDonate: "Binance Bağış",
  metamaskDonate: "Metamask Bağış",
  founder: "Kurucu",
  loading: "Yükleniyor..."
};

const content = { tr };

export default content; 